version: '2'
services:
  nginx:
    image: nginx:1.13.8
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build: .
    container_name: django
    command: ./wait-for-it.sh db:5432 -- ./src/start.sh
    depends_on:
      - db
    volumes:
      - ./src:/src
    expose:
      - "8000"

  db:
    image: postgres:10.1
    container_name: pg
