# Generated by Django 2.0.1 on 2018-06-18 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('age_group', models.CharField(max_length=40)),
                ('topic', models.CharField(blank=True, max_length=50)),
                ('site', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=50)),
                ('date', models.CharField(blank=True, max_length=50)),
                ('time', models.CharField(blank=True, max_length=50)),
                ('volunteer_app', models.CharField(blank=True, max_length=50)),
                ('volunteer_app_deadline', models.CharField(blank=True, max_length=50)),
                ('volunteer_time', models.CharField(blank=True, max_length=100)),
                ('volunteer_exp', models.CharField(blank=True, max_length=100)),
                ('student_app', models.CharField(blank=True, max_length=50)),
                ('student_app_deadline', models.CharField(blank=True, max_length=50)),
                ('nomination', models.CharField(blank=True, max_length=50)),
                ('nomination_deadline', models.CharField(blank=True, max_length=50)),
                ('cost', models.CharField(max_length=50)),
                ('scholarship_app', models.CharField(blank=True, max_length=50)),
                ('scholarship_app_deadline', models.CharField(blank=True, max_length=50)),
                ('donations_accepted', models.BooleanField()),
                ('donations_link', models.CharField(blank=True, max_length=200)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.Contact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Organization')),
            ],
        ),
    ]
