# Generated by Django 2.0.1 on 2018-06-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20180618_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='program',
            name='student_app',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='program',
            name='student_app_deadline',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='program',
            name='volunteer_app',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
