# Generated by Django 2.0.1 on 2018-06-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20180618_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
