# Generated by Django 2.0.1 on 2018-06-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20180623_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='start',
            field=models.DateField(null=True),
        ),
    ]
