# Generated by Django 2.0.1 on 2018-06-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_auto_20180623_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
